<?php

namespace Fuad\Reactor\Generators;

use Illuminate\Support\Facades\File;

class AuthGenerator
{
    public static function generate(): void
    {
        // 1. توليد الـ AuthController
        $stub = File::get(__DIR__ . '/../../stubs/auth_controller.stub');
        $path = app_path('Http/Controllers/AuthController.php');
        File::ensureDirectoryExists(dirname($path));
        File::put($path, $stub);

        // 2. إضافة مسارات API تلقائياً إلى routes/api.php
        self::appendApiRoutes();
    }

    protected static function appendApiRoutes(): void
    {
        $routesPath = base_path('routes/api.php');

        if (! File::exists($routesPath)) {
            return;
        }

        $routesCode = <<<PHP


// Authentication Routes Generated by Fuad Reactor
use App\Http\Controllers\AuthController;

Route::post('/register', [AuthController::class, 'register']);
Route::post('/login', [AuthController::class, 'login']);

Route::middleware('auth:sanctum')->group(function () {
    Route::post('/logout', [AuthController::class, 'logout']);
    Route::get('/me', [AuthController::class, 'me']);
});
PHP;

        $currentRoutes = File::get($routesPath);

        // تجنب تكرار إضافة المسارات
        if (! str_contains($currentRoutes, 'AuthController::class')) {
            File::append($routesPath, $routesCode);
        }
    }
}